modLoader="javafml"
loaderVersion="[36,)"
license="GPL v3"
[[mods]]
modId="gttools"
version="${file.jarVersion}"
displayName="GregigTools"
logoFile="logo.png"
credits="Thanks to Greg"
authors="BioAst"
description='''
'''

[[dependencies.gttools]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.gttools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
